all tests pass
deep-foundation/deepclient pull request #27
Opened 2023-05-30 19:32 UTC by CEHR2005

2023-07-05 01:10 UTC, Konard commented on python/deepclient/deep_client.py
> +from .gql.serial import generate_serial
```suggestion
from .gql.serial import generate_serial

```

2023-07-05 01:14 UTC, Konard requested changes

2023-07-05 01:14 UTC, Konard commented on python/deepclient/deep_client.py
> +    async def serial(self, operations: List[Dict[str, Any]], returning: str = "from_id id to_id type_id value", silent: bool = False):
Serial should accept object (dict), not arguments directly.

https://github.com/deep-foundation/deeplinks/blob/c6495c15a3abe66392f40121e969859d440cbcef/imports/client.tsx#L805

2023-07-11 08:11 UTC, Konard requested changes

2023-07-11 08:11 UTC, Konard commented on python/deepclient/deep_client.py
> +    async def insert(self, record: Dict, options: Dict = {}) -> Dict:
https://github.com/deep-foundation/deeplinks/blob/26cb67fd59fcc4f727b80356fa417fcbe53455ea/imports/client.tsx#L682-L700

What is record? As I see in the original source code, we have only options.

2023-07-16 15:26 UTC, Archelunch commented
- Проект не запускается из-за проблемы импортов
```

Traceback:
../../../../../../miniconda3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_deep_client.py:3: in <module>
    from deepclient import DeepClient, DeepClientOptions
../deepclient/__init__.py:1: in <module>
    from .deep_client import DeepClient
../deepclient/deep_client.py:4: in <module>
    from .query import generate_query, generate_query_data
../deepclient/query.py:2: in <module>
    from gql import gql
E   ModuleNotFoundError: No module named 'gql'
```
- в gql отсутствует __init__.py
- в gql/mutation.py попытка импорта самого себя `from gql import gql`
- в /tests/test_deep_client.py:12 передается ключ авторизации к инстанс. Так лучше не делать, даже если это тестовый

2023-07-30 20:04 UTC, Archer-Lotos commented on python/tests/test_deep_client.py
> +            url='https://3006-deepfoundation-dev-hqmvurfv4le.ws-eu98.gitpod.io/gql',
let's put it in env
and in the readme, so that it is clear what is needed for the tests


example:

python-dotenv==1.0.0 

```
import os
from dotenv import load_dotenv

class TestDeepClient(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        load_dotenv()
        transport = AIOHTTPTransport(
            url=os.getenv('URL_GQL'),
            headers={'Authorization': 'Bearer %s' % (os.getenv('BEARER_TOKEN'))}
        )
        client = Client(transport=transport, fetch_schema_from_transport=True)
```

.env


```
URL_GQL='https://3006-deepfoundation-dev-dxwefxwetsq.ws-eu102.gitpod.io/gql'
BEARER_TOKEN=eyJh...
```

2023-07-30 20:44 UTC, Lotos2021 commented
https://github.com/deep-foundation/deepclient/blob/main/python/setup.py#L8

empty install_requires list

2023-07-31 00:12 UTC, Lotos2021 commented
https://github.com/deep-foundation/deepclient/blob/main/.github/workflows/main.yml#L44

bug when building the package, the generate_gql_operations folder is not added

fix: add generate_gql_operations/__init__.py

2023-08-10 14:03 UTC, Konard requested changes
`python/deepclient/generate_gql_operations` should be renamed to `python/deepclient/gql_operations`

2023-08-10 14:03 UTC, konard commented on python/deepclient/deep_client.py
> +    async def update(self, condition: Dict, record: Dict, options: Dict = {}) -> Dict:
```suggestion
    async def update(self, exp: Dict, value: Dict, options: Dict = {}) -> Dict:
```

2023-08-10 17:23 UTC, CEHR2005 commented on python/deepclient/deep_client.py
> +    async def update(self, condition: Dict, record: Dict, options: Dict = {}) -> Dict:
Done

2023-08-12 14:58 UTC, Konard approved these changes

2023-08-12 14:58 UTC, merged